### ISSUE TITLE
Using Gestures on SlideMenuView - how to close

### ISSUE THREAD

**Issue by stefandevo** [XAM-Consulting/SlideOverKit#1]
Hi, great component! Thanks for open sourcing it.

Your samples show a SlideMenuView with image/label combinations that would present buttons in real life. I added a gesture recogniser on the StackLayouts to catch a command. Although this works perfectly I would need a way to close the SlideMenuView afterwards.... Any suggestion on doing this. I now have a command that binds with my view model + a tapped event handler for all these panels that do a HideWithoutAnimations(). Is this the way to do it?

Btw: I using this on Android (AppCompat).

**Comment by jessejiang0214** [comment]
I have a suggestion, which I often used in my projects. 
In you ViewModel, you can set a Action property like

Public Action CloseMenu { get; set; }

In your MenuView override OnBindingContextChanged and set ()=>{ this.HideWithoutAnimations ();} to CloseMenu property.

Then in your button Command in ViewMode, just invoke CloseMenu will be fine.

**Comment by stefandevo** [comment]
ok thanks for the suggestion. Would be nice if you could implement a Command in the controls for it to call to do the same.

**Comment by stefandevo** [comment]
Another idea: add a Visbility property to the SlideMenuView. That way I could make a binding to this property from the model. Thanks for the suggestion @rid00z ! [sitting next to me in the Evolve setting]

**Comment by james-lavery** [comment]
How are you guys binding the SlideMenuView to the ViewModel? Are you creating a ViewModel for the SlideMenuView itself, or are you referring to the ViewModel for the Page containing the SlideMenuView? I'm struggling to work out how to do this.

**Comment by jessejiang0214** [comment]
@james-lavery I create a ViewModel for SlideMenuView. But you can binding to Page's BindingContext, just override page's OnBindingContextChanged function.
