### ISSUE TITLE
Latest library is not supporting iOS v9.3.2

### ISSUE THREAD

**Issue by dhirengoyalcybage** [XAM-Consulting/SlideOverKit#10]
![slideroverkit_issues](https://cloud.githubusercontent.com/assets/18323265/16335310/7c42c766-3a23-11e6-9e28-0008c0f07b63.png)
Hi,
I m unable to use the library for iOS v9.3.2.
It is working till v9.3.1.
Can u update the library for latest OS support.

Also i am getting ~387 errors in Resource.Designer.cs, as snap attached.

**Comment by rid00z** [comment]
Interesting, anymore info?


On Friday, 24 June 2016, dhirengoyalcybage <notifications@github.com> wrote:

> Hi,
> I m unable to use the library for iOS v9.3.2.
> It is working till v9.3.1.
> Can u update the library for latest OS support.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/XAM-Consulting/SlideOverKit/issues/10>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABeXvVhCjOiXvsNWGQpSysBkbHta4bEIks5qO6zegaJpZM4I9ou1>
> .
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by dhirengoyalcybage** [comment]
**iOS project:**
I am using SlideMenuView control with MenuOrientations="BottomToTop" and when i m using my app in iphone/ipad till v9.3.1 its working fine but in latest updated device (v9.3.2) its not working and opening drawer and no exception is there to trace.

**Android project:**
Errors are there in Resource.Designer.cs while building xamarin project as mentioned and only in the lines of the libraries if i remove these lines and run the project, it builds successfully and gets deployed and again error in next build. So same process again and again.

**Comment by dhirengoyalcybage** [comment]
Any updates as I am unable to create APK due to above errors in Resource.Designer.cs

**Comment by rid00z** [comment]
@dhirengoyalcybage This is not actually to do with SlideOverKit, it's to do with your project. It looks like your Xamarin.Forms in your Android package did not update. Need to make sure you update Xamarin.Forms in your Android project.
