### ISSUE TITLE
Popup Page throwing Object Reference Error in Android Platform 

### ISSUE THREAD

**Issue by KathirveluM** [XAM-Consulting/SlideOverKit#12]
Hi,
I have downloaded the Latest SlidOverKit Samples and Deployed the same in iOS and Android Platform. 
1. The sample is working fine in iOS platform but **throwing Object Reference Error in Android Platform** . 
2. Suggest on how to pass Observable Collections and Objects to Popup Page to bind the controls?
3. While saving on the popup button, how to update the parent page details (which opened the popup)?

For Your Information: 
I have checked the two months older SlidOverKit source and its working fine with Android Platform as well. 
Kindly help me to resolve the same. 
[Screenshot for Reference:](https://1drv.ms/i/s!ArmvMJfDes95iDCirQD_0_mTHwz9)
**Output Trace:**
07-27 16:45:39.582 I/MonoDroid(10866): UNHANDLED EXCEPTION:
07-27 16:45:39.585 I/MonoDroid(10866): System.NullReferenceException: Object reference not set to an instance of an object.
07-27 16:45:39.585 I/MonoDroid(10866):   at Xamarin.Forms.Platform.Android.Platform.GetRenderer (Xamarin.Forms.VisualElement bindable) [0x00000] in C:\BuildAgent3\work\aad494dc9bc9783\Xamarin.Forms.Platform.Android\Platform.cs:289 
07-27 16:45:39.585 I/MonoDroid(10866):   at SlideOverKit.Droid.SlideOverKitDroidHandler.LayoutPopup () [0x0006a] in D:\SlideOverKit-master\SlideOverKit.Droid\SlideOverKitDroidHandler.cs:177 
07-27 16:45:39.585 I/MonoDroid(10866):   at SlideOverKit.Droid.SlideOverKitDroidHandler.<AddPopup>b__14_0 (System.String key) [0x000e8] in D:\SlideOverKit-master\SlideOverKit.Droid\SlideOverKitDroidHandler.cs:141 
07-27 16:45:39.585 I/MonoDroid(10866):   at SlideOverKit.MenuContainerPage.ShowPopup (System.String name) [0x0000e] in D:\SlideOverKit-master\SlideOverKit\MenuContainerPage.cs:54 
07-27 16:45:39.585 I/MonoDroid(10866):   at SlideOverKit.MoreSample.PopOverPage.<.ctor>b__0_1 () [0x00026] in D:\SlideOverKit-master\SlideOverKitMoreSamples\SlideOverKit.Sample\Pages\PopOverPage.cs:34 
07-27 16:45:39.586 I/MonoDroid(10866):   at Xamarin.Forms.Command+<>c__DisplayClass3_0.<.ctor>b__0 (System.Object o) [0x00000] in C:\BuildAgent3\work\aad494dc9bc9783\Xamarin.Forms.Core\Command.cs:36 
07-27 16:45:39.586 I/MonoDroid(10866):   at Xamarin.Forms.Command.Execute (System.Object parameter) [0x00000] in C:\BuildAgent3\work\aad494dc9bc9783\Xamarin.Forms.Core\Command.cs:70 
07-27 16:45:39.586 I/MonoDroid(10866):   at Xamarin.Forms.MenuItem.Activate () [0x00010] in C:\BuildAgent3\work\aad494dc9bc9783\Xamarin.Forms.Core\MenuItem.cs:77 
07-27 16:45:39.586 I/MonoDroid(10866):   at Xamarin.Forms.Platform.Android.GenericMenuClickListener.OnMenuItemClick (IMenuItem item) [0x00000] in C:\BuildAgent3\work\aad494dc9bc9783\Xamarin.Forms.Platform.Android\GenericMenuClickListener.cs:18 
07-27 16:45:39.586 I/MonoDroid(10866):   at Android.Views.IMenuItemOnMenuItemClickListenerInvoker.n_OnMenuItemClick_Landroid_view_MenuItem_ (IntPtr jnienv, IntPtr native__this, IntPtr native_item) [0x00011] in /Users/builder/data/lanes/3415/7db2aac3/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.IMenuItem.cs:295 
07-27 16:45:39.586 I/MonoDroid(10866):   at (wrapper dynamic-method) System.Object:88931f3b-e273-4be4-8d0f-1c32b323d7cc (intptr,intptr,intptr)
07-27 16:45:39.601 W/art     (10866): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
07-27 16:45:39.607 D/Mono    (10866): DllImport searching in: '__Internal' ('(null)').
07-27 16:45:39.607 D/Mono    (10866): Searching for 'java_interop_jnienv_throw'.
07-27 16:45:39.607 D/Mono    (10866): Probing 'java_interop_jnienv_throw'.
07-27 16:45:39.607 D/Mono    (10866): Found as 'java_interop_jnienv_throw'.
The thread 'Unknown' (0x5) has exited with code 0 (0x0).
The thread 'Unknown' (0x3) has exited with code 0 (0x0).
An unhandled exception occured.

**Configuration Details:**
- Windows 8.1 Pro (64-bit)
-  Vs 2015 Enterprise
- Visual studio Xamarin Version- 4.1.1.3
- Xamarin Android - 6.1.1.1

**Comment by jessejiang0214** [comment]
Fixed c3a78122483d38c51665306b4f2835911fb8e447
