### ISSUE TITLE
How to use the drop down menu when using a TabbedPage Control

### ISSUE THREAD

**Issue by msmrajesh** [XAM-Consulting/SlideOverKit#14]
Hi,

With reference to this statement "If your page need to inherit from other base pages in your solution, you must implement IMenuContainerPage interface and you need to create the renderer pages for each platforms. It won't too hard, just copy codes from sample, you can follow the SlideDownMenuPage page in sample code to do this."

I am trying to use a TabbedPage Control and then show this drop down menu from the top. I have followed this stop in a form where the page inherits from a ContentPage and it works fine.

works fine
`public partial class DropDownPage : ContentPage , IMenuContainerPage` 

But when using the same technique to inherit it from a TabbedPage the pages are all merged and the tabs are not displayed individually.

does not work
`public partial class MainPage : TabbedPage , IMenuContainerPage`

Is there any solution to fix this problem when inheriting from a  TabbedPage Control. Kindly help me out since it is important to achieve this functionality.

Thanks,

Rajesh.

**Comment by jessejiang0214** [comment]
Well TabbedPage is MultiPage<Page>, the IMenuContainerPage should be used for single page. 
You can add menu in child page of TabbedPage. It will be the same.
