### ISSUE TITLE
Would it be possible to change SlideOverKit so that no base class is required?

### ISSUE THREAD

**Issue by escamoteur** [XAM-Consulting/SlideOverKit#18]
Hi Michael,

I just wonder if it would be possible to change SlideOverKit so that Pages wold not have to Inherit from SlideOverPage but only from an ISlideOverPage which would be an empty interface that would allow you to use extension methods on this interface type.

What do you think about that?

Best
Thomas

**Comment by jessejiang0214** [comment]
Well, we have the interface to do that called IPopupContainerPage
Here is the sample SlideOverKit/SlideOverKitMoreSamples/SlideOverKit.Sample/Pages/SlideDownMenuPage.cs
Only you need to do is create that page renderer like this
SlideOverKit/SlideOverKitMoreSamples/iOS/Renderer/PageImpInterfaceRendereiOS.cs

**Comment by escamoteur** [comment]
Thanks, will check it out
