### ISSUE TITLE
Multiple slideovers on same page

### ISSUE THREAD

**Issue by PiotrRomanskiPC** [XAM-Consulting/SlideOverKit#19]
Hello,
is it possible to have two slideovers working on single page? I'd like to use one for navigation drawer (drawn from left or right) and on one of my pages I need also slideover drawn from top as secondary menu.

But the events to control slideover are on page level so this can be a problem. Is there a way?

**Comment by jessejiang0214** [comment]
No for SlideMenuView, but you can use two more SlidePopupViews in one Page. 
In you case, I suggest you to use MasterDetail page with SlideMenuView from top in Detail page.
