### ISSUE TITLE
SlideMenuView Visibility Toggle?

### ISSUE THREAD

**Issue by stefandevo** [XAM-Consulting/SlideOverKit#2]
I now have a button in my action bar to call up the SlideMenuView. I would prefer that when the button is tapped the view is showed. I can do this with the ShowMenuAction. However, when I tap the button again I want to have a HideMenuAction.
Thing is, that there is no way (to my knowledge) to actually know that the view is showed. If I keep my own variable to use the Button as a toggle that I can control the show and hide. However, when the user makes a swipe up to close the menu that way I have no clue whether the view is showed or not.
Would be nice that there is a property on the SlideMenuView (and probably on all other controls as well) that gives a clue about visibility.

**Comment by jessejiang0214** [comment]
Well we can do that, thanks for your idea.

**Comment by jessejiang0214** [comment]
Check this d8bf4054d3477862719c1130c58dea94325d9263

**Comment by stefandevo** [comment]
Great!! Thx.

**Comment by Matti-Koopa** [comment]
How do I use this? I tried: `HideMenuAction = () => { throw new Exception("HIDE"); };`

But that doesn't fire when I close the SlideMenu.
The only way I seem to get a hide-event is by doing this on my SlideMenuView:
`protected override void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            if (propertyName == "X")
                throw new Exception("HIDE");
            base.OnPropertyChanged(propertyName);
        }`

...but this is hardly a solution.

I'm using UWP with Xamarin Forms.

**Comment by Matti-Koopa** [comment]
Okay, apparently it doesn't work in the MenuContainerPage constructor. It works afterwards.

**Comment by kenny128** [comment]
@Matti-Koopa I know this was a long time a go but do you remember where you changed HideMenuAction and ShowMenuAction?

**Comment by Matti-Koopa** [comment]
I'll just post my whole code. It provides nice event handlers.

```
using SlideOverKit;
using System;
using System.Collections.Generic;
using System.Text;

namespace MagWien.DART.Pages
{
    public class MenuContainerEventPage : MenuContainerPage
    {
        protected override void OnAppearing()
        {
            base.OnAppearing();
            InitMenu();
        }

        private Action OriginalShowAction;
        private Action OriginalHideAction;

        private void InitMenu()
        {
            if (!InitMenuDone)
            {
                OriginalShowAction = ShowMenuAction;
                OriginalHideAction = HideMenuAction;
                ShowMenuAction = () => NewShowAction();
                HideMenuAction = () => NewHideAction();
                InitMenuDone = true;
            }
        }

        private void NewShowAction()
        {
            MenuEventArgs e = new MenuEventArgs();
            RaiseOnMenuShow(e);
            if (!e.Cancel && OriginalShowAction != null)
                OriginalShowAction();
        }

        private void NewHideAction()
        {
            MenuEventArgs e = new MenuEventArgs();
            RaiseOnMenuHide(e);
            if (!e.Cancel && OriginalHideAction != null)
                OriginalHideAction();
        }

        private bool InitMenuDone;

        public class MenuEventArgs : EventArgs
        {
            /// <summary>
            /// Aktion abbrechen
            /// </summary>
            public bool Cancel { get; set; }
        }

        /// <summary>
        /// Wird ausgelöst, wenn Menü eingeblendet wird
        /// </summary>
        public event EventHandler<MenuEventArgs> OnMenuShow;
        public void RaiseOnMenuShow(MenuEventArgs e)
        {
            OnMenuShow?.Invoke(this, e);
        }

        /// <summary>
        /// Wird ausgelöst, wenn Menü ausgeblendet wird
        /// </summary>
        public event EventHandler<MenuEventArgs> OnMenuHide;
        public void RaiseOnMenuHide(MenuEventArgs e)
        {
            OnMenuHide?.Invoke(this, e);
        }
    }
}
```
