### ISSUE TITLE
Menu Container Page with 2 slide menus

### ISSUE THREAD

**Issue by mick1313** [XAM-Consulting/SlideOverKit#21]
I have a MenuContainer page with a hamburger menu on the left, and an account menu on the right...  When a button is clicked I set the page SlideMenu to the appropriate SlideOverView (leftMenu, rightMenu).  and then call ShowMenu().  But nothing happens.

If I set the SlideMenu to leftMenu in the constructor, I always see that menu.  and Vice versa.  How can I get the slideMenu to change from right to left and back again depending on what the user selects?

**Comment by jessejiang0214** [comment]
The Container page is design for showing one SlideView only. There is no way to add another one.
