### ISSUE TITLE
Adding menus to pages defined with xaml?

### ISSUE THREAD

**Issue by shayo** [XAM-Consulting/SlideOverKit#27]
I'm trying to use SlideOverKit and add a menu to an existing content page that is defined with xaml.
However, I can't derive the main class as MenuContainerPage because I get the following error:
"Partial declarations of XXX must not specify different base classess"
In all the examples provided, all container pages did not have xaml of their own (only their corresponding menu views).
How can I add a menu to a page that is already defined with xaml?

**Comment by ItalianRaptor** [comment]
I'm getting the same error for the same scenario.
Any suggestions?

**Comment by jessejiang0214** [comment]
Using "t:SlidePopupView" follow this sample code 
https://github.com/XAM-Consulting/SlideOverKit/blob/master/SlideOverKitMoreSamples/SlideOverKit.Sample/Pages/PopOverWithTriangleView.xaml

**Comment by jessejiang0214** [comment]
And in code behind your page class should inherit from SlideMenuView
