### ISSUE TITLE
Open right side master from ViewModel

### ISSUE THREAD

**Issue by stackunderflows** [XAM-Consulting/SlideOverKit#28]
Is it possible to open the rights side master menu from a ViewModel? The example all show opening it from the code-behind. If it's possible, can you show an example? Not sure if it matters but I'm using Prism and so my ViewModel has to inherit from BasePageModel.

**Comment by jessejiang0214** [comment]
I assume in your ViewModel you can access the page, you can create a function in page to open the menu and then call that function from ViewModel

**Comment by rampyodm** [comment]
That's the problem - you don't have access to the page from the ViewModel.

**Comment by jessejiang0214** [comment]
What's MVVM framework did you use?

**Comment by stackunderflows** [comment]
Prism
