### ISSUE TITLE
LeftToRight or RightToLeft push functionality

### ISSUE THREAD

**Issue by ChaseCarlile** [XAM-Consulting/SlideOverKit#3]
I need a custom navigation bar in my app, so I'm trying to find a suitable way to use this component with SetHasNavigationBar = false (but with a custom view along the top).  Is there a way to push the detail page when using a full height master page (like http://www.jasny.net/bootstrap/examples/navmenu-push/)?  In the sample, the RightToLeft menu appears over the detail page, so if you have a hamburger button at the top of the detail page it would get covered.  In lieu of pushing the page, is there a way to specify an offset at the top so that menu master won't cover my custom nav bar?  I've tried TopMargin, but it doesn't appear to hook into these menu orientations.  Thanks for any help.

**Comment by jessejiang0214** [comment]
Hi Chase,

I didn't find the perfect solution, but you can use the sample code in QuickInnerMenuView to do this.

First, you need to set IsFulScreen = false,
Then set orientation = MenuOrientation.RightToLeft
You must set WidthRequest and HeighRequest, and TopMargin.
In this situation HeighRequest is import, you should make sure HeighRequest can cover all devices' height, You can set it bigger then normal page size.

**Comment by ChaseCarlile** [comment]
Interesting idea.  I'll give that a shot.  Thanks for your time.
