### ISSUE TITLE
BottomToUp sliding menu toggle superpose bottomBar on iOS

### ISSUE THREAD

**Issue by Piteryo** [XAM-Consulting/SlideOverKit#33]
If you have sliding menu (like QuickInnerMenu in sample) and bottom tabbed menu then on iOS toggle is placed at the bottom of the screen, not at the top of tabbed menu, so it interferes menu. On android everything works perfectly

**Comment by jessejiang0214** [comment]
This issue is by design, MenuContainerPage is based on Page not TabbedPage, so we cannot do more about this.
I come up with a solution, you can change DraggerButtonHeight in iOS, so that it will over the tabbed bar.
