### ISSUE TITLE
Fresh and SlideoverKit

### ISSUE THREAD

**Issue by tallmanBS** [XAM-Consulting/SlideOverKit#35]
I can only find a couple forum posts, but none give solution.  

How can I call a SlidePopupView (as in sample with popoverview), from the FreshBasePageModel, when i don't have the showmenu and other functions in the class MenuContainerPage.  I've tried to create my own Menucontainerpage with a base of FreshBasePageModel but haven't been able to do it because the ShoeMenuAction is Null when I attempt to call it assuming because that's part of the custom renderer.

Others describe using messaging, but I'm still not sure how to popup overtop of a model page.
Thank you for both FreshMvvm and SlideoverKit.

**Comment by jessejiang0214** [comment]
Well As SlideOverKit doesn't have bindable properties for show and hide popups, so it means you cannot control it from ViewModel. 

But there is a solution for that, in FreshBasePageModel you can use this.CurrentPage property to get current page, then convert current page as MenuContainerPage, then call ShowMenu();

**Comment by tallmanBS** [comment]
I'm not sure what it means when you say 
then convert current page as MenuContainerPage, then call ShowMenu();

How is this done?
I've tried in the buttonclick of the model
 `       public Command buttonClicked
        {
            get
            {
                return new Command(() =>
                {
                    var page = this.CurrentPage as MenuContainerPage;
                    page.ShowMenu();
                });
            }
        }`

        But this is not going to work.  I also cannot change the ContentPage to MenuContainerPage
`    public partial class TestPage : ContentPage`
Because it's a partial class and the generated code also refers to it as a ContentPage.

How would I get the MenuContainerPage built? 

Thank you for your help as I think others have needed this as well.  I really like slideoverkit and hope I can use.

**Comment by jessejiang0214** [comment]
You TestPage must inherit from MenuContainerPage or IMenuContainerPage, otherwise you cannot use SlideOverKit.
Here is the document http://www.xam-consulting.com/slideoverkit-xamarin-forms/

**Comment by tallmanBS** [comment]
I've brought in all the renders into my project as the document specified, and the classes.  Where I'm stuck is I've built my own MenuContainerPage as follows using the FreshMvvm Base.
`    public class FreshMvvmMenuContainerPage : FreshBasePageModel, IMenuContainerPage, IPopupContainerPage
    {
`
But because the FreshBasePageModel doesn't have a Page base, I can't get it to call the renderer when i execute the ShowPopupAction.

I can grab the Page from CurrentPage in FreshBasePageModel, but I'm lost on how to connect it to the renderer without having MenuContainerPage be the base.  I know I'm doing something wrong, but not sure what.

**Comment by tallmanBS** [comment]
I am happy to have some progress so I'll post here in case someone else finds this and its helpful.  So to have the popup show inside my Model and ModelPage was alot simpler than I thought.

1. I changed my ContentPage on the Xaml.cs to 
`        public partial class TestPage : MenuContainerPage
    {
        public TestPage()
        {
            InitializeComponent();
            PopupViews.Add("FirstPopup", new PopOverView());

        }
        public void OnClicked()
        {
            ShowPopup("FirstPopup");
        }
    }
`

2. Changed the Xaml using sample provided for SlideOverKit and 
`<?xml version="1.0" encoding="utf-8" ?>
<local:MenuContainerPage xmlns="http://xamarin.com/schemas/2014/forms" 
                         xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
                         x:Class="MyApp.Pages.TestPage"
	xmlns:local="clr-namespace:MyApp.Classes.SlideOverKit;assembly=MyApp" >

    <ContentPage.Content>
        <StackLayout>
            <StackLayout Orientation="Horizontal">
                <StackLayout Orientation="Vertical">
                    <Entry Text="Xamarin.Forms " />
                    <Entry Text="_______" />
                    <Button Text="PopupTest2" Clicked="OnClicked"/>
                </StackLayout>
            </StackLayout>
        </StackLayout>
    </ContentPage.Content>
</local:MenuContainerPage>`

This allowed the page to operate.  Then if I wanted to open the popup from inside the model, I just changed the button onclicked to use the command and included.
`        public Command buttonClicked
        {
            get
            {
                return new Command(() =>
                {

                    var page = this.CurrentPage as MenuContainerPage;
                    page.ShowPopup("FirstPopup");
            }
        }
`
Although after more consideration, I think generally this would mean the view logic of the popup would be in the model, and should be in the xaml.cs as part of the view.  Regarldess.

I did not pursue making the popup actually use a model/view.  I think this would be too much work for the amount of use this will have.  For just the couple screens, I decided just to not use model phylisopy for the popup.

**Comment by jessejiang0214** [comment]
You can create a Bindable property in xaml.cs file, and then binding this property with ViewModel, like ShowPopup, when this property changed you can show or hide the menu from XAML code behind.

**Comment by ernestochaves** [comment]
I tried adding a property.  https://github.com/XAM-Consulting/SlideOverKit/pull/79 but I'm stuck on knowing why it isn't building for me. Also, I noticed a bunch of PR from jessicarich1980 that never got merged, so I assuming mine won't be accepted either anytime soon.
But you can probably do what I did, subclass the container page and add the bindable property. I am using it that way and it works.
