### ISSUE TITLE
How to get slide menu views exact height in Xamarin.Forms for Android platform

### ISSUE THREAD

**Issue by productXF** [XAM-Consulting/SlideOverKit#45]
I am using Xamarin.forms with SlideOverKit(https://github.com/XAM-Consulting/SlideOverKit) . SlideOverKit uses static values for HeightRequest & 
WidthRequest for slide menu. I want to dynamically set the height as per menu content, for this I am making use of custom renderer of library & overriding the 
OnMeasure() for Android. 
I am suppose to get child views height by measuring them as per below code but it always return me the parent/screen height. I tried 
differnet combinations of MeasureSpec mode & size but unable to get exact height of child elements.

SlideMenuDroidRenderer.cs inside SlideOverKit.Droid project:- 

    protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
			{
				 int mWidth = 0, mHt = 0;
				 int childWidthMeasureSpec = MeasureSpec.MakeMeasureSpec(MarginLayoutParams.WrapContent, MeasureSpecMode.Exactly);
				 int childHeightMeasureSpec = MeasureSpec.MakeMeasureSpec(MarginLayoutParams.WrapContent, MeasureSpecMode.Exactly);
				  for (int i = 0; i < ChildCount; i++)
						{
							Android.Views.View child = GetChildAt(i);
							if (child.Visibility != ViewStates.Gone)
							{
								child.Measure(childWidthMeasureSpec, childHeightMeasureSpec);                   
								mWidth += child.MeasuredWidth;
								mHt += child.MeasuredHeight;
								
							}
						}
					SetMeasuredDimension(width, height);
			}
After it calls OnLayout(), I use MeasuredHeight & MeasuredWidth to set the slidemenu height & width.

If anyone knows how to get exact size of menu view in custom renderer of Xamarin.Forms ? 

TIA.

**Comment by jessejiang0214** [comment]
Well before page rendered, there is no way to calculate the child view height or width. I'm not sure if Xamarin added some new API to do that.
