### ISSUE TITLE
How to change DraggerButtonHeight from outside constructor?

### ISSUE THREAD

**Issue by prince01** [XAM-Consulting/SlideOverKit#46]
I binded DraggerButtonHeight to viewmodel property
`private int _draggerButtonHeight;
        public int DraggerButtonHeight
        {
            get { return _draggerButtonHeight; }
            set { SetProperty(ref _draggerButtonHeight, value); }
        }`.
The size I set in constructor remains even after I change value of this property.
How to resize it?

**Comment by jessejiang0214** [comment]
This cannot be changed in runtime by design.

**Comment by prince01** [comment]
pity. Thanks though
