### ISSUE TITLE
Right side menu view

### ISSUE THREAD

**Issue by hashimks** [XAM-Consulting/SlideOverKit#48]
Hello,

Just wanted to know whether for a navigation page, the right side menu will be shown as complete height of the screen or is the side menu height start from below the navigation bar to the lower end?

**Comment by hashimks** [comment]
Its already there.. thanks

**Comment by hashimks** [comment]
Sorry.. its there..
i checked in android

**Comment by hashimks** [comment]
Its not full view in android, but full view in iOS.. can you please help me?

**Comment by jessejiang0214** [comment]
You can use SlidePopupView.AdjustY to change the height in different platforms

**Comment by hashimks** [comment]
@jessejiang0214  Can you please give me an example?

**Comment by hashimks** [comment]
can u pls help me? I am stuck here

**Comment by hashimks** [comment]
Hello?

**Comment by rid00z** [comment]
@hashimks are the samples not enough? Just closing this because it's not a issue.

**Comment by Thanghand** [comment]
Hi, I have the same issue  the slideMenu LeftToRight in Android does not has the full screen. It always below NavigationBar
