### ISSUE TITLE
Gestures not working

### ISSUE THREAD

**Issue by lyuboasenov** [XAM-Consulting/SlideOverKit#49]
Hello, I'm trying to incorporate SlideOverKit in a Xamarin.Forms and the gestures doesn't seems to be working. The SlideMenuView doesn't catch the focus at all. 

Here is a test project. 
https://github.com/lyuboasenov/test-slide-over-kit.git

I've copied the files from your sample application.

**Comment by jessejiang0214** [comment]
Did you use SlideOverKit in a Shared project not PCL project?

**Comment by lyuboasenov** [comment]
SlideOverKit is used via Nuget packages. The forms project is a net standard class library while the android project is an Android App project.

**Comment by lyuboasenov** [comment]
SlideOverKit is used via Nuget packages. The forms project is a net standard class library while the android project is an Android App project.

**Comment by T3zler** [comment]
Hi. I face the same issue. Updated a project from PCL to .Net Standard project (as well as a Xamarin forms update - running 2.4.0.282) and the "drag-able" gesture has stopped working! i.e. we have a TopToBottom menu we could slide up but now that gesture doesn't work. I added the following code from your sample to a button and the menu does slide up. As soon as a tap is registered it closes instantly also, i.e. I can't drag closed or anything like that. 

`if (SlideMenu.IsShown)
                    {
                        HideMenuAction?.Invoke();
                    }
                    else
                    {
                        ShowMenuAction?.Invoke();
                    }`

For now we are having to update the app so it works on click instead but preferred the drag behaviour as it gave a better feel.

Be interested to know what others have experienced using this from a .Net standard library?

**Comment by jessejiang0214** [comment]
Hi @lyuboasenov 
I downloaded your project in Mac environment, I cannot build with Visual Studio for Mac. I don't have the Windows environment currently, so I cannot do more testings. 

From my feeling, it caused by the wrong environment, can you create a project using Xamarin.From project template?

**Comment by mrmiagi0101** [comment]
I had the same Problem with Forms 2.4 sr1. You have to override the OnTouchEvent of the SlideMenuDroidRenderer. Instead of return base.OnTouchEvent(e), you have to return true. At the moment all seems to run again, but still testing...

**Comment by jessejiang0214** [comment]
Thx @mrmiagi0101 you're right, I fixed this for Xamarin.Forms 2.4

**Comment by T3zler** [comment]
@jessejiang0214 great news. When will this see a Nuget release?
