### ISSUE TITLE
UWP .NET dependencies not declared

### ISSUE THREAD

**Issue by ghuntley** [XAM-Consulting/SlideOverKit#5]
Run this https://github.com/onovotny/ReferenceGenerator and bump your minor + push to NuGet to fix.

**Comment by jessejiang0214** [comment]
Fixed it

**Comment by ghuntley** [comment]
:star:

**Comment by rid00z** [comment]
:star::star::star::star::star: 

Jesse was upset he only got one star, needs 5 like a hotel system.

**Comment by rid00z** [comment]
Um, yeh I couldn't see that this is fixed.
