### ISSUE TITLE
Does not appear to be .NET Standard 2.0 compatible

### ISSUE THREAD

**Issue by marcusts** [XAM-Consulting/SlideOverKit#60]
Hi, this package gives yellow flag warnings when included in a .NET Standard 2.0 library  Is it supposed to be compatible? If not, when can it be made compatible?

Thanks!

**Comment by jessejiang0214** [comment]
I think you can ignore it, SlideOverKit just dependency on Xamarin.Forms and didn't use other .NET API like refection, file APIs, etc, so It should be used in PCL or .NET Standard. I have no idea why it flags warnings, but I think it doesn't matter.
