### ISSUE TITLE
Warning .net Standard

### ISSUE THREAD

**Issue by TedMobile** [XAM-Consulting/SlideOverKit#61]
Hi 
wondering if you have had this issue and how to solve it.

Moved our xamarin solution to .net standard and we get this warning.(which we are ignoring) but would be nice to to have fixed if possible

NU1701: Package 'SlideOverKit 2.1.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

Any plans to make it .net standard 2.0 compatible?

thanks

**Comment by jessejiang0214** [comment]
2.1.6 will fix this.
