### ISSUE TITLE
SlideOverKit-2.1.5 cannot use Xamarin.Forms 2.5 (or needs clarifying please)

### ISSUE THREAD

**Issue by jackjackson** [XAM-Consulting/SlideOverKit#69]
Michael
The Nuget version of SlideOverKit-2.1.5 has no dependencies listed so I thought it required Xamarin.Forms 2.5.0.280555 (the latest at this time) Now I see that this is not the case and your 2.1.5 project has a dependency on the PageRenderer of Xamarin.Forms 2.4 (no context parameter in ctor) However we have multiple reasons to be on 2.5.0.280555.

So my question is, firstly, do I have this correct. The SlideOverKit-2.1.5.dll requires 2.4.0.18342, right? Secondly, if we rebuild SlideOverKit-2.1.5 with the uplift to Xamarin.Forms 2.5 (similar to the revision below) can you see any issues?

The Git revision of 1st March:
https://github.com/XAM-Consulting/SlideOverKit/commit/7909207ddc4ec27bb5971271d1c26c15d2fc48cf

**Comment by jessejiang0214** [comment]
Yes, you're right. I haven't tested with Xamarin.Forms 2.4, but it seems to be an issue.

**Comment by jessejiang0214** [comment]
I have fixed this in 2.1.6.1
