### ISSUE TITLE
Page on UWP stays blank (light grey) on UWP

### ISSUE THREAD

**Issue by escamoteur** [XAM-Consulting/SlideOverKit#7]
Hi,

I'm just trying to get my App running on UWP. Unfortunately My Page stays blank when I inherit it from MenuContainerPage. It works in Android but not on UWP. 

Any Idea?

Best
Thomas

**Comment by jessejiang0214** [comment]
Did you add assemblies into Xamarin.Form.Init() function?

                // you'll need to add `using System.Reflection;`
                List<Assembly> assembliesToInclude = new List<Assembly>();

                //Now, add in all the assemblies your app uses
                assembliesToInclude.Add(typeof(SlideOverKit.MenuContainerPage).GetTypeInfo().Assembly);
                assembliesToInclude.Add(typeof(SlideOverKit.UWP.MenuContainerPageUWPRenderer).GetTypeInfo().Assembly);
                //Also do this for all your other 3rd party libraries

                Xamarin.Forms.Forms.Init(e, assembliesToInclude);

**Comment by escamoteur** [comment]
Why do I have to do this manually?

**Comment by jessejiang0214** [comment]
Well, that is Xamarin.Form's issue, we must do that 
https://developer.xamarin.com/guides/xamarin-forms/platform-features/windows/installation/universal/

**Comment by escamoteur** [comment]
I see, but I'm still in debug mode, but I did it and no change

**Comment by escamoteur** [comment]
Ok, it seems there is more than one problem. I now figured out that the Problem only occurs when I assign the Menu in the Page Constructor.
I now tried to build a small project for reproduction. Here my Page is displayed, but 
[SlideUWPTest.zip](https://github.com/XAM-Consulting/SlideOverKit/files/292989/SlideUWPTest.zip)
nothing happens at all when I call ShowMenu on UWP. It works on Android though.

**Comment by jessejiang0214** [comment]
Fixed this

**Comment by escamoteur** [comment]
So there way a problem :-) ALready on nuget?

**Comment by jessejiang0214** [comment]
Yes, 2.1.1 https://www.nuget.org/packages/SlideOverKit/
