### ISSUE TITLE
Using SlideOverKit without inheriting from MenuContainerPage

### ISSUE THREAD

**Issue by noelfernandes** [XAM-Consulting/SlideOverKit#72]
Hi,
I working on a Xamarin Forms project where I have a mainpage (xaml - all my pages are xaml) that is heavily dependent and inherits from the ContentPage. It is dependent in the sense that I am using other plugins like DLToolKit and FFImageLoading and these work pretty well.

With SlideOverKit, I would like to implement either the RightSideMaster/Menu or the Popup menu. Based on the examples, both these require the calling page (in my case the mainpage) to be inheriting from MenuContainerPage which for me results in the following errors.....

_Partial declarations of 'MainPage' must not specify different base classes._

Is there any way that I can I can implement either of the menus without inheriting from the MenuContainerPage? Maybe by instantiating it in the calling page?

Thanks in advance.

**Comment by jessejiang0214** [comment]
Check this sample https://github.com/XAM-Consulting/SlideOverKit/blob/master/SlideOverKitMoreSamples/SlideOverKit.Sample/Pages/SlideDownMenuPage.cs
It should be what you want.

**Comment by noelfernandes** [comment]
Hi @jessejiang0214, 
Thanks so much for getting back to me on this.
I'm afraid inheriting from the IMenuContainerPage still doesn't work. I have tried it in a basic Xamarin Forms solution which I have uploaded [here](https://github.com/noelfernandes/XamarinFormsTrials/tree/master/SOKTrials).
I would greatly appreciate if you could take a look at the solution and advise on what I am missing out.

**NOTE: I am currently focusing on the Android solution so I haven't tested on iOS as yet.**
