### ISSUE TITLE
SlideOverMenu or RightSideMaster not being displayed.

### ISSUE THREAD

**Issue by noelfernandes** [XAM-Consulting/SlideOverKit#76]
Hi,
I'm afraid inheriting from the IMenuContainerPage doesn't work. As per the recommendation in [this issue](https://github.com/XAM-Consulting/SlideOverKit/issues/72) I have tested it in a basic Xamarin Forms (Android) solution which I have uploaded [here](https://github.com/noelfernandes/XamarinFormsTrials/tree/master/SOKTrials).

I would greatly appreciate if you could take a look at the solution and advise on what I am missing out.
I'm running on:
Xamarin Forms 2.5.1.527436
SlideOverKit 2.1.6.1

**NOTE: I am currently focusing on the Android solution so I haven't tested on iOS as yet**

**Comment by jessejiang0214** [comment]
You didn't implement Android renderer by yourself. Check this
https://github.com/XAM-Consulting/SlideOverKit/blob/master/SlideOverKitMoreSamples/Droid/Renderer/PageImpInterfaceRendererDroid.cs
