### ISSUE TITLE
Default constructor not found for type SlideOverKit.Droid.MenuContainer Page Droid Renderer

### ISSUE THREAD

**Issue by phamthanhtong** [XAM-Consulting/SlideOverKit#77]
I'm using Xamarin Forms ver 2.3.4.247 on Visual Studio for Mac ver 17.4, and updated SlideOverKit ver 2.1.6.1
But when I ran on Android app, this error was raised:
`Default constructor not found for type SlideOverKit.Droid.MenuContainer Page Droid Renderer`

How to fix it?

**Comment by jessejiang0214** [comment]
You should update Xamarin.Forms above 2.5
