### ISSUE TITLE
Use SlideOverKit as Satellite menu?

### ISSUE THREAD

**Issue by Korayem** [XAM-Consulting/SlideOverKit#9]
Is it possible to customize SlideOverKit to be used as a Satellite menu?
![image](https://cloud.githubusercontent.com/assets/198332/16165502/9915e6d2-34e4-11e6-96fa-25f39a77c08b.png)

**Comment by rid00z** [comment]
@Korayem SlideOverKit wouldn't be the best option for a control like this.
