### ISSUE TITLE
The Action delegates ShowMenuAction / HideMenuAction are null

### ISSUE THREAD

**Issue by Muhi** [XAM-Consulting/SlideOverKit#96]
When following the sample in my app. 
ContentPage, IMenuContainerPage
And including .
public Action HideMenuAction { get; set; }
public Action ShowMenuAction{get; set; }

The Hide and show are null all the time so Invoke() does nothing. And I can't see what I am donig wrong.

**Comment by thiagoparabas** [comment]
Me too....

**Comment by Muhi** [comment]
@thiagoparabas
I was able to get this working. I missed something on my side during the impl.
I forgot the PageImpInterfaceRenderer for both the (IOS / Android)
and set the typeof to your view ExportRenderer(typeof(myPageView)
After doing that it all worked hope that helps

**Comment by thiagoparabas** [comment]
Please share exemple.
